// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251004172754_AddKappiModule")]
    partial class AddKappiModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Modules.Kappi.Models.AnonymousGallery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("access_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("short_code");

                    b.HasKey("Id")
                        .HasName("pk_anonymous_galleries");

                    b.HasIndex("AccessKey")
                        .IsUnique()
                        .HasDatabaseName("ix_anonymous_galleries_access_key");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_anonymous_galleries_expires_at");

                    b.HasIndex("ShortCode")
                        .IsUnique()
                        .HasDatabaseName("ix_anonymous_galleries_short_code");

                    b.ToTable("anonymous_galleries", (string)null);
                });

            modelBuilder.Entity("api.Modules.Kappi.Models.Gallery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("short_code");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_galleries");

                    b.HasIndex("ShortCode")
                        .IsUnique()
                        .HasDatabaseName("ix_galleries_short_code");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_galleries_user_id");

                    b.ToTable("galleries", (string)null);
                });

            modelBuilder.Entity("api.Modules.Kappi.Models.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AnonymousGalleryId")
                        .HasColumnType("uuid")
                        .HasColumnName("anonymous_gallery_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<Guid?>("GalleryId")
                        .HasColumnType("uuid")
                        .HasColumnName("gallery_id");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("MediaType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("media_type");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("s3key");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_media");

                    b.HasIndex("AnonymousGalleryId")
                        .HasDatabaseName("ix_media_anonymous_gallery_id");

                    b.HasIndex("GalleryId")
                        .HasDatabaseName("ix_media_gallery_id");

                    b.HasIndex("S3Key")
                        .IsUnique()
                        .HasDatabaseName("ix_media_s3key");

                    b.ToTable("media", (string)null);
                });

            modelBuilder.Entity("api.Modules.User.Models.ApiToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_api_token");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_api_token_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_api_token_user_id");

                    b.ToTable("api_token", (string)null);
                });

            modelBuilder.Entity("api.Modules.User.Models.OneTimePassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_one_time_password");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_one_time_password_user_id");

                    b.HasIndex("Code", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_one_time_password_code_user_id");

                    b.ToTable("one_time_password", (string)null);
                });

            modelBuilder.Entity("api.Modules.User.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_token_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_token_user_id");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("api.Modules.User.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("api.Modules.Kappi.Models.Gallery", b =>
                {
                    b.HasOne("api.Modules.User.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_galleries_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Modules.Kappi.Models.Media", b =>
                {
                    b.HasOne("api.Modules.Kappi.Models.AnonymousGallery", "AnonymousGallery")
                        .WithMany("Media")
                        .HasForeignKey("AnonymousGalleryId")
                        .HasConstraintName("fk_media_anonymous_galleries_anonymous_gallery_id");

                    b.HasOne("api.Modules.Kappi.Models.Gallery", "Gallery")
                        .WithMany("Media")
                        .HasForeignKey("GalleryId")
                        .HasConstraintName("fk_media_galleries_gallery_id");

                    b.Navigation("AnonymousGallery");

                    b.Navigation("Gallery");
                });

            modelBuilder.Entity("api.Modules.User.Models.ApiToken", b =>
                {
                    b.HasOne("api.Modules.User.Models.User", "User")
                        .WithMany("ApiTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_token_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Modules.User.Models.OneTimePassword", b =>
                {
                    b.HasOne("api.Modules.User.Models.User", "User")
                        .WithMany("OneTimePasswords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_one_time_password_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Modules.User.Models.RefreshToken", b =>
                {
                    b.HasOne("api.Modules.User.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Modules.Kappi.Models.AnonymousGallery", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("api.Modules.Kappi.Models.Gallery", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("api.Modules.User.Models.User", b =>
                {
                    b.Navigation("ApiTokens");

                    b.Navigation("OneTimePasswords");
                });
#pragma warning restore 612, 618
        }
    }
}
