services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-kappigg_db}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-kappigg_user}
    volumes:
      - kappigg_db_volume:/var/lib/postgresql/data:rw
    ports:
      - "15432:5432"
  mailer:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3,lambda
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - LAMBDA_EXECUTOR=docker-reuse
    ports:
      - "4566:4566"
    volumes:
      - ./localstack-setup:/etc/localstack/init/ready.d
      - ./lambda-metadata-extractor:/tmp/lambda-metadata-extractor
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  kappigg_db_volume: