/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type AnonymousGalleryDto = {
  /**
   * @format uuid
   */
  id: string;
  shortCode: string;
  /**
   * @format date-time
   */
  expiresAt: string;
  /**
   * @format date-time
   */
  createdAt: string;
  media: MediaListResponse;
};

export type ApiTokenResponse = {
  token: string;
  refreshToken: string;
  user: UserDto;
};

export type ConfirmUploadDto = {
  /**
   * @format uuid
   */
  mediaId: string;
};

export type CreateAnonymousGalleryResponse = {
  /**
   * @format uuid
   */
  galleryId: string;
  shortCode: string;
  accessKey: string;
  /**
   * @format date-time
   */
  expiresAt: string;
};

export type CreateGalleryDto = {
  isPublic: boolean;
  password: string | null;
};

export type ErrorResponse = {
  code: string;
};

export type GalleryDto = {
  /**
   * @format uuid
   */
  id: string;
  shortCode: string;
  isPublic: boolean;
  hasPassword: boolean;
  /**
   * @format date-time
   */
  createdAt: string;
  media: MediaListResponse;
};

export type GalleryListResponse = {
  galleries: GalleryDto[];
  /**
   * @format int32
   */
  totalCount: number;
};

export type GuidResponse = {
  /**
   * @format uuid
   */
  id: string;
};

export type MediaDto = {
  /**
   * @format uuid
   */
  id: string;
  mediaType: string | null;
  /**
   * @format int32
   */
  width: number | null;
  /**
   * @format int32
   */
  height: number | null;
  /**
   * @format int64
   */
  fileSize: number | null;
  downloadUrl: string;
  /**
   * @format date-time
   */
  createdAt: string;
};

export type MediaListResponse = {
  media: MediaDto[];
  /**
   * @format int32
   */
  totalCount: number;
};

export type ProblemDetails = {
  type?: string | null;
  title?: string | null;
  /**
   * @format int32
   */
  status?: number | null;
  detail?: string | null;
  instance?: string | null;
};

export type RequestUploadUrlDto = {
  fileName: string;
  contentType: string;
};

export type SuccessResponse = {
  message: string;
};

export type TokenRefreshDto = {
  /**
   * @minLength 1
   */
  refreshToken: string;
};

export type UpdateGalleryDto = {
  isPublic: boolean;
  password: string | null;
};

export type UploadUrlResponse = {
  /**
   * @format uuid
   */
  mediaId: string;
  uploadUrl: string;
  s3Key: string;
};

export type UserDto = {
  /**
   * @format uuid
   */
  id: string;
  email: string;
};

export type UserInfoResponse = {
  user: UserDto;
};

export type UserLoginDto = {
  email: string;
  /**
   * @maxLength 6
   * @minLength 6
   */
  code: string;
};

export type UserRegistrationDto = {
  email: string;
};

export type VerifyGalleryPasswordDto = {
  password: string;
};
